import { buildFullDisplayName } from '@/lib/config'
import type { CategoryResult } from '@/lib/types'

export type RankedPhone = CategoryResult['phones'][number]

export interface CategoryRule {
  label: string
  value: string
}

export interface CategorySeo {
  heading: string
  shortLabel: string
  scoreLabel: string
  titleSuffix: string
  lead: (year: number) => string
  basis: string
  rules: CategoryRule[]
  metric?: (p: RankedPhone) => string | null
}

const RELEASE_WINDOW: CategoryRule = { label: 'Release window', value: 'Current and previous calendar year' }
const MIN_SCREEN: CategoryRule = { label: 'Screen', value: '5.5 inches or larger' }
const BRAND_LIMIT: CategoryRule = { label: 'Brand limit', value: 'Up to 2 phones per brand' }

const fmtInt = (n: number) => n.toLocaleString('en-US')

const priceMetric = (p: RankedPhone) => (p.price_usd != null ? `$${fmtInt(Math.round(p.price_usd))}` : null)

const VALUE_BASIS =
  'Ranked by value score, which compares a phone\'s hardware against similarly priced phones. Phones without one are ranked by a composite of battery capacity, main camera resolution and AnTuTu score. Prices are tracked estimates and can differ from retailer prices.'

export const CATEGORY_SEO: Record<string, CategorySeo> = {
  'camera-phones': {
    heading: 'Best Camera Phones',
    shortLabel: 'Camera',
    scoreLabel: 'Camera Score',
    titleSuffix: 'Ranked by Camera Score',
    lead: year => `Best camera phones of ${year} ranked by camera score:`,
    basis:
      'Ranked by camera score, generated by our AI model from each phone\'s listed camera specifications. Phones without a camera score are ranked by a fallback spec composite of camera resolution, OIS, chip performance and charging speed.',
    rules: [
      { label: 'Camera data', value: 'Main camera resolution listed' },
      MIN_SCREEN,
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'battery-life': {
    heading: 'Best Battery Life Phones',
    shortLabel: 'Battery Life',
    scoreLabel: 'Battery Score',
    titleSuffix: 'Ranked by Battery Score',
    lead: year => `Best battery life phones of ${year} ranked by battery score:`,
    basis:
      'Ranked by battery score, generated by our AI model from listed battery specifications. Phones without a battery score are ranked by raw capacity in mAh.',
    metric: p => (p.battery_capacity ? `${fmtInt(p.battery_capacity)}mAh` : null),
    rules: [
      { label: 'Battery data', value: 'Capacity listed' },
      MIN_SCREEN,
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'gaming-phones': {
    heading: 'Best Gaming Phones',
    shortLabel: 'Gaming',
    scoreLabel: 'Performance Score',
    titleSuffix: 'Ranked by Performance',
    lead: year => `Best gaming phones of ${year} ranked by performance:`,
    basis:
      'Ranked by performance score, generated by our AI model from listed chipset and benchmark data. Phones without one are ranked by AnTuTu score, with gaming-optimized hardware boosted.',
    metric: p => (p.antutu_score ? `${(p.antutu_score / 1_000_000).toFixed(1)}M AnTuTu` : null),
    rules: [
      { label: 'Benchmark data', value: 'AnTuTu score listed' },
      MIN_SCREEN,
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'under-300': {
    heading: 'Best Phones Under $300',
    shortLabel: 'Under $300',
    scoreLabel: 'Value Score',
    titleSuffix: 'Ranked by Value',
    lead: year => `Best phones under $300 in ${year}, ranked by value:`,
    basis: VALUE_BASIS,
    metric: priceMetric,
    rules: [
      { label: 'Price', value: 'Tracked price up to $300' },
      MIN_SCREEN,
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'under-500': {
    heading: 'Best Phones Under $500',
    shortLabel: 'Under $500',
    scoreLabel: 'Value Score',
    titleSuffix: 'Ranked by Value',
    lead: year => `Best phones under $500 in ${year}, ranked by value:`,
    basis: VALUE_BASIS,
    metric: priceMetric,
    rules: [
      { label: 'Price', value: 'Tracked price up to $500' },
      MIN_SCREEN,
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'lightweight': {
    heading: 'Lightest Smartphones',
    shortLabel: 'Lightweight',
    scoreLabel: 'Lightness Score',
    titleSuffix: 'Ranked by Weight',
    lead: year => `The lightest smartphones of ${year} by listed weight:`,
    basis: 'Ranked purely by listed weight, lightest first. No AI score is involved in this ranking.',
    metric: p => (p.weight_g ? `${Math.round(p.weight_g)}g` : null),
    rules: [
      { label: 'Weight', value: '100 to 185 g' },
      MIN_SCREEN,
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'foldables': {
    heading: 'Best Foldable Phones',
    shortLabel: 'Foldables',
    scoreLabel: 'Overall Score',
    titleSuffix: 'Ranked by Overall Score',
    lead: year => `Best foldable phones of ${year} ranked by overall score:`,
    basis:
      'Ranked by overall score, generated by our AI model from listed specifications. Phones without one are ranked by AnTuTu score. Only foldable form factors are included.',
    rules: [
      { label: 'Form factor', value: 'Foldable' },
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'compact-phones': {
    heading: 'Best Compact Phones',
    shortLabel: 'Compact',
    scoreLabel: 'Performance Score',
    titleSuffix: 'Ranked by Performance',
    lead: year => `Best compact phones of ${year} (screens up to 6.3") ranked by performance:`,
    basis:
      'Ranked by performance score, generated by our AI model from listed chipset and benchmark data. Phones without one are ranked by AnTuTu score. Only phones with 5.0 to 6.3 inch screens are included.',
    metric: p => (p.screen_size ? `${p.screen_size}"` : null),
    rules: [
      { label: 'Screen', value: '5.0 to 6.3 inches' },
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
  'fast-charging': {
    heading: 'Fastest Charging Phones',
    shortLabel: 'Fast Charging',
    scoreLabel: 'Charging Score',
    titleSuffix: 'Ranked by Wattage',
    lead: year => `Fastest charging phones of ${year} by wired wattage:`,
    basis: 'Ranked purely by maximum wired charging wattage. Wireless charging is not counted, and no AI score is involved.',
    metric: p => (p.fast_charging_w ? `${p.fast_charging_w}W` : null),
    rules: [
      { label: 'Charging', value: '30W or faster, wired' },
      MIN_SCREEN,
      RELEASE_WINDOW,
      BRAND_LIMIT,
    ],
  },
}

const DESCRIPTION_TAIL = 'Compare specs and prices on Specmob.'
const DESCRIPTION_MAX = 158

function joinNames(items: string[]): string {
  if (items.length <= 1) return items[0] ?? ''
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`
}

function topEntries(slug: string, phones: RankedPhone[], count: number): string[] {
  const { metric } = CATEGORY_SEO[slug]
  return phones.slice(0, count).map(p => {
    const name = buildFullDisplayName(p)
    const value = metric?.(p)
    return value ? `${name} (${value})` : name
  })
}

export function latestReleaseYear(phones: RankedPhone[]): number {
  return phones.reduce((max, p) => Math.max(max, p.release_year ?? 0), 0) || new Date().getFullYear()
}

export function categoryTitle(slug: string, year: number): string {
  const seo = CATEGORY_SEO[slug]
  return `${seo.heading} ${year}: ${seo.titleSuffix}`
}

export function categoryDescription(slug: string, year: number, phones: RankedPhone[]): string {
  const lead = CATEGORY_SEO[slug].lead(year)

  for (let n = Math.min(3, phones.length); n >= 1; n--) {
    const candidate = `${lead} ${joinNames(topEntries(slug, phones, n))}. ${DESCRIPTION_TAIL}`
    if (candidate.length <= DESCRIPTION_MAX || n === 1) return candidate
  }

  return `${lead.replace(/:$/, '.')} ${DESCRIPTION_TAIL}`
}

export function categoryIntro(slug: string, phones: RankedPhone[]): string {
  const leaders = topEntries(slug, phones, 3)
  const verb = leaders.length === 1 ? 'leads' : 'lead'
  const prefix = leaders.length ? `Right now ${joinNames(leaders)} ${verb} the ranking. ` : ''
  return `${prefix}${CATEGORY_SEO[slug].basis}`
}
